import Link from 'next/link'
import './globals.css'
import MenuDeNavegacion from '@/components/MenuDeNavegacion'

export const metadata = {
  title: 'Instagram',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>
        {/* <MenuDeNavegacion /> */}

        {children}

      </body>
    </html>
  )
}
