import Link from 'next/link'
import './globals.css'

export const metadata = {
  title: 'Instagram',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>
        <h1>Instagram</h1>

        <nav>
          <ul>
            <li>
              <Link className='text-cyan-700' href="/">Inicio</Link>
            </li>
            <li>
              <Link className='text-cyan-700' href="/contacto">Contacto</Link>
            </li>
            <li>
              <Link className='text-cyan-700' href="/productos">Productos</Link>
            </li>
          </ul>
        </nav>

        {children}

        <footer>Soy el footer de la pagina</footer>
      </body>
    </html>
  )
}
